# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Recipe.create(name: "Skillet-Roasted Chicken and Potatoes", course: "main", ingredients: ["4 large bone-in, skin-on chicken thighs", "Kosher salt and freshly ground black pepper", "2½ cups buttermilk, shaken", "Good olive oil", "2 tablespoons Dijon mustard", "1 tablespoon dry white wine, such as Chablis", "1½ teaspoons fresh thyme leaves", "¹⁄₈ teaspoon sweet Hungarian paprika", "1 pound medium Yukon Gold potatoes, unpeeled, sliced ¼ inch thick", "1 tablespoon minced garlic (3 cloves)", "2 tablespoons minced fresh parsley", "1 tablespoon chopped fresh chives"], time: 315, steps: "At least 4 hours (but not more than 12 hours) before you plan to serve, sprinkle the chicken all over with 1 teaspoon salt and ½ teaspoon pepper. Place in a 1-gallon sealable plastic bag and pour in the buttermilk. Seal the bag and massage it lightly to be sure the chicken is coated with the buttermilk. Place in the refrigerator to marinate.

Preheat the oven to 350 degrees. Pour 2 tablespoons olive oil in an unheated 12-inch cast-iron skillet and tilt the pan so the oil covers the bottom. Lift the thighs out of the buttermilk, letting any excess buttermilk drip off, and place them in the skillet, skin side up, in one layer. Discard the marinade. In a small bowl, combine the mustard and wine and brush it on the top of the chicken. Sprinkle with the thyme, paprika, 1 teaspoon salt, and ½ teaspoon pepper. Place the skillet in the oven and roast the chicken for 30 minutes.

Using tongs, transfer the chicken to a plate and put the potatoes, garlic, 1 teaspoon salt, and ½ teaspoon pepper into the skillet. Toss to coat with the pan juices then spread the potatoes out. Return the chicken to the skillet, placing it on the potatoes. Roast 30 minutes longer, until the chicken registers 155 degrees on an instant-read thermometer. Transfer just the chicken to a plate and cover loosely with aluminum foil to keep warm. Return the skillet to the oven, raise the temperature to 425 degrees, and roast the potatoes for 15 minutes, until they’re tender and starting to brown. Return the chicken to the pan and sprinkle with the parsley, chives, and extra salt. Serve hot from the skillet.", skill_level: "beginner")